# Generated by Django 4.2.16 on 2026-04-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views_count',
        ),
    ]
